version: '3'

services:
  api:
    image: ghcr.io/nils-witt/s-plan_api:latest
    restart: always
    environment:
      # API Self
      API_URL: "https://api.splan.nils-witt.de"

      # Developer Settings
      APIDOC: "false"

      #PWA
      PWA_URL: "https://pwa.splan.example.de"

      #Display
      DISPLAY_URL: "https://display.splan.example.de"
      #Notifications

      ##Telegram
      TELEGRAM: "false"
      TELEGRAM_KEY: ""
      TELEGRAM_VALIDATION_URL: "https://pwa.splan.example.de/pages/linkTelegram.html"

      # FCM
      FCM: "false"
      FCM_URL: "https://url_server.firebaseio.com"
      FCM_CREDENTIALS: "/home/node/app/keys/fcm_key.json"

      # WebPush
      WEBPUSH: "true"
      VAPID_PUBLIC: "VAPID_PUBLIC"
      VAPID_PRIVATE: "VAPID_PRIVATE"
      VAPID_SUBJECT: "mailto:admin@example.de"

      # LDAP
      LDAP: "true"

      LDAP_HOST: "ldap://127.0.0.1:389"
      LDAP_ROOT: "DC=domain,DC=local"
      LDAP_DOMAIN: "domain"

      LDAP_STUDENTSGROUP: "CN=Students,DC=domain,DC=local"
      LDAP_TEACHERGROUP: "CN=Teachers,DC=domain,DC=local"

      LDAP_USER: "user"
      LDAP_PASS: "pass"

      LDAP_TLS: "false"
      LDAP_CA_PATH: "/home/node/app/keys/ldap-ca.pem"

      # MySQL
      SQL_PORT: "3306"
      SQL_HOST: "mysql"
      SQL_USER: "splan"
      SQL_PASS: ""
      SQL_DB: "splan"

      # Moodle
      MOODLE: "false"
      MOODLE_HOST: "moodle.example.de"
      MOODLE_PATH: ""
      MOODLE_KEY: "KEY"
    volumes:
      - ./logs/api/:/usr/src/splan/log
      - ./configs/api/keys:/usr/src/splan/keys
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: "splan"
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: "splan"
    volumes:
      - ./data/database:/var/lib/mysql
  pwa:
    image: ghcr.io/nils-witt/s-plan_pwa:latest
    environment:
      API_URL: "https://api.splan.example.de"
      TG_BOT_URL: "https://t.me/BOT"
      MOODLE_URL: "https://moodle.splan.example.de"
  display:
    image: ghcr.io/nils-witt/s-plan_display:latest
    restart: always
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
    links:
      - mysql
    depends_on:
      - mysql
  reverseProxy:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/proxy/conf:/etc/nginx
      - ./configs/proxy/certs:/etc/ssl/certs
    links:
      - api
      - pwa
      - display
      - phpmyadmin
    depends_on:
      - api
      - pwa
      - display
      - phpmyadmin